//user-defined headers
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/core/misc/python/pyopencv_async.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/core/misc/python/pyopencv_cuda.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/core/misc/python/pyopencv_umat.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/flann/misc/python/pyopencv_flann.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/ml/misc/python/pyopencv_ml.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/dnn/misc/python/pyopencv_dnn.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/features2d/misc/python/pyopencv_features2d.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/videoio/misc/python/pyopencv_videoio.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/objdetect/misc/python/pyopencv_objdetect.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/stitching/misc/python/pyopencv_stitching.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/video/misc/python/pyopencv_video.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/gapi/misc/python/python_bridge.hpp"
#include "/Users/raphaeltolila/PycharmProjects/assistant Video/Assistant_Jarvis/opencv/modules/gapi/misc/python/pyopencv_gapi.hpp"
